"""Generate LaTeX tables + headline macros for the report from the eval JSON.

Reads  ../results/eval_all_v100.json
Writes tables/macros.tex, tables/aggregate.tex, tables/per_problem.tex

These are \\input by main.tex so the paper's numbers always equal the measured
data. Re-run after the evaluation finishes.
"""
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
JSON_PATH = os.path.join(HERE, "..", "results", "eval_all_v100.json")
TAB_DIR = os.path.join(HERE, "tables")

FAST_P = [1.0, 1.5, 2.0, 3.0]

# Short human-friendly operator names + one-line technique notes (display only).
NOTES = {
    (1, 6):  ("Matmul (large K)",       "Triton split-K ($SK{=}20$); cuBLAS ceiling"),
    (1, 9):  ("Tall-skinny matmul",     "Triton tile, mask-free; cuBLAS ceiling"),
    (1, 16): ("Matmul $A^\\top B$",      "Triton single tl.trans"),
    (1, 18): ("Matmul $A^\\top B^\\top$", "Reformulated $(BA)^\\top$; store-side trans"),
    (1, 23): ("Softmax (wide row)",     "streaming online softmax"),
    (1, 36): ("RMSNorm",                "2-pass streaming"),
    (1, 47): ("Sum reduction",          "cub-bound"),
    (1, 50): ("Conv2D (11x11 s4)",      "Triton implicit GEMM"),
    (1, 56): ("Conv2D (asymmetric)",    "Triton implicit GEMM"),
    (1, 61): ("ConvTranspose3D",        "Triton gather GEMM"),
    (1, 76): ("Conv1D (dilated)",       "Triton implicit GEMM"),
    (1, 82): ("Depthwise Conv2D",       "Triton direct 3x3 (beats cuDNN)"),
    (1, 86): ("Depthwise-sep Conv2D",   "Triton dw + cuBLAS pw"),
    (1, 93): ("Masked cumsum",          "fused mask+scan"),
    (1, 97): ("Scaled dot-prod attn",   "Triton flash-attn (D-tiled)"),
    (2, 1):  ("Conv+ReLU+Bias",         "cuDNN + fused epilogue"),
    (2, 12): ("Gemm+Mul+LeakyReLU",     "cuBLAS-bound"),
    (2, 21): ("Conv+Scale+Sig+GN",      "5 passes -> 2"),
    (2, 22): ("Matmul+Clamp+LSE+Mish",  "algebraic + 1-pass post"),
    (2, 40): ("Matmul+Scale+Residual",  "$ys{+}y\\to y(s{+}1)$"),
    (2, 45): ("Gemm+Sigmoid+LSE",       "two GEMMs dominate"),
    (2, 56): ("Matmul+Sigmoid+Sum",     "cuBLAS-bound"),
    (2, 66): ("Matmul+Dropout+Softmax", "dropout-RNG fix"),
    (2, 88): ("Gemm+GN+Swish+Mul+Sw",   "5 passes -> 2"),
    (2, 99): ("Gemm+GELU+Softmax",      "cuBLAS-bound"),
    (3, 1):  ("MLP",                    "torch.compile (Inductor) wrap"),
    (3, 28): ("Vision Transformer",     "torch.compile (Inductor) wrap"),
    (3, 43): ("minGPT causal attn",     "SDPA is\\_causal"),
    (3, 44): ("minGPT block",           "SDPA + gelu(tanh)"),
    (3, 48): ("Mamba-2 (return Y)",     "param-only contraction hoist"),
}


def esc(s):
    return (str(s).replace("\\", "\\textbackslash{}")
            .replace("_", "\\_").replace("%", "\\%")
            .replace("&", "\\&").replace("#", "\\#"))


def fmt(v, suffix=""):
    if v is None:
        return "--"
    return f"{v:.2f}{suffix}" if suffix else f"{v:.3f}"


def tex_x(v):
    """Speedup value formatted as e.g. 1.05$\\times$ for LaTeX."""
    if v is None:
        return "--"
    return f"{v:.2f}$\\times$"


def geomean(vals):
    vals = [v for v in vals if v and v > 0]
    if not vals:
        return None
    return math.exp(sum(math.log(v) for v in vals) / len(vals))


def main():
    with open(JSON_PATH) as f:
        rows = json.load(f)
    os.makedirs(TAB_DIR, exist_ok=True)

    n = len(rows)
    n_correct = sum(1 for r in rows if r.get("correct"))
    n_compiled = sum(1 for r in rows if r.get("compiled"))
    sp_e = [r["speedup_eager"] for r in rows if r.get("correct") and r.get("speedup_eager")]
    sp_c = [r["speedup_compile"] for r in rows if r.get("correct") and r.get("speedup_compile")]
    gm_e, gm_c = geomean(sp_e), geomean(sp_c)

    def fastp(key, p):
        return sum(1 for r in rows if r.get("correct") and r.get(key) and r[key] >= p)

    fe = {p: fastp("speedup_eager", p) for p in FAST_P}
    fc = {p: fastp("speedup_compile", p) for p in FAST_P}

    # ---- macros.tex ---------------------------------------------------------
    def pct(x):
        return f"{x/n*100:.0f}\\% ({x}/{n})"
    macros = [
        "% auto-generated by generate_tables.py -- do not edit",
        f"\\renewcommand{{\\NumProblems}}{{{n}}}",
        f"\\renewcommand{{\\NumCorrect}}{{{n_correct}}}",
        f"\\renewcommand{{\\GeoMeanEager}}{{{tex_x(gm_e)}}}",
        f"\\renewcommand{{\\GeoMeanCompile}}{{{tex_x(gm_c)}}}",
        f"\\renewcommand{{\\FastOneEager}}{{{pct(fe[1.0])}}}",
        f"\\renewcommand{{\\FastTwoEager}}{{{pct(fe[2.0])}}}",
        "",
    ]
    with open(os.path.join(TAB_DIR, "macros.tex"), "w") as f:
        f.write("\n".join(macros))

    # ---- aggregate.tex ------------------------------------------------------
    agg = []
    agg.append("% auto-generated by generate_tables.py")
    agg.append("\\begin{table}[t]")
    agg.append("\\centering")
    agg.append("\\caption{Aggregate V100 FP32 results over the fixed 30-problem set. "
               "\\texttt{fast\\_p} = fraction correct \\emph{and} speedup $\\ge p$.}")
    agg.append("\\label{tab:aggregate}")
    agg.append("\\begin{tabular}{lcccc}")
    agg.append("\\toprule")
    agg.append("Metric & \\multicolumn{4}{c}{Value} \\\\")
    agg.append("\\midrule")
    agg.append(f"Compiled & \\multicolumn{{4}}{{c}}{{{n_compiled}/{n}}} \\\\")
    agg.append(f"Correct & \\multicolumn{{4}}{{c}}{{{n_correct}/{n}}} \\\\")
    agg.append(f"Geo-mean speedup (vs.\\ eager) & \\multicolumn{{4}}{{c}}"
               f"{{{tex_x(gm_e)}}} \\\\")
    agg.append(f"Geo-mean speedup (vs.\\ compile) & \\multicolumn{{4}}{{c}}"
               f"{{{tex_x(gm_c)}}} \\\\")
    agg.append("\\midrule")
    agg.append("\\texttt{fast\\_p} & $p{=}1.0$ & $p{=}1.5$ & $p{=}2.0$ & $p{=}3.0$ \\\\")
    agg.append("\\midrule")
    agg.append("vs.\\ eager & " + " & ".join(
        f"{fe[p]}/{n}" for p in FAST_P) + " \\\\")
    agg.append("vs.\\ compile & " + " & ".join(
        f"{fc[p]}/{n}" for p in FAST_P) + " \\\\")
    agg.append("\\bottomrule")
    agg.append("\\end{tabular}")
    agg.append("\\end{table}")
    with open(os.path.join(TAB_DIR, "aggregate.tex"), "w") as f:
        f.write("\n".join(agg))

    # ---- per_problem.tex ----------------------------------------------------
    rows_sorted = sorted(rows, key=lambda r: (r.get("level", 9), r.get("problem_id", 999)))
    pp = []
    pp.append("% auto-generated by generate_tables.py")
    pp.append("\\begin{table*}[t]")
    pp.append("\\centering")
    pp.append("\\caption{Per-problem V100 FP32 results. Speedups are "
              "baseline/kernel; $\\ge 1.0$ in \\textbf{bold}. "
              "``Technique'' is the dominant strategy the agent chose.}")
    pp.append("\\label{tab:perproblem}")
    pp.append("\\footnotesize")
    pp.append("\\begin{tabular}{clllccrrr}")
    pp.append("\\toprule")
    pp.append("Lv & PID & Operator & Technique & Correct & "
              "Kernel (ms) & Eager (ms) & Sp.\\ eager & Sp.\\ compile \\\\")
    pp.append("\\midrule")
    cur_lv = None
    for r in rows_sorted:
        lv, pid = r.get("level"), r.get("problem_id")
        if cur_lv is not None and lv != cur_lv:
            pp.append("\\midrule")
        cur_lv = lv
        name, tech = NOTES.get((lv, pid), (esc(r.get("solution", "")), ""))
        se, sc = r.get("speedup_eager"), r.get("speedup_compile")

        def bold(v):
            if v is None:
                return "--"
            s = f"{v:.2f}$\\times$"
            return f"\\textbf{{{s}}}" if v >= 1.0 else s
        correct = "\\checkmark" if r.get("correct") else "$\\times$"
        pp.append(f"{lv} & {pid} & {name} & {tech} & {correct} & "
                  f"{fmt(r.get('kernel_ms'))} & {fmt(r.get('eager_ms'))} & "
                  f"{bold(se)} & {bold(sc)} \\\\")
    pp.append("\\bottomrule")
    pp.append("\\end{tabular}")
    pp.append("\\end{table*}")
    with open(os.path.join(TAB_DIR, "per_problem.tex"), "w") as f:
        f.write("\n".join(pp))

    print(f"tables written for n={n}, correct={n_correct}, "
          f"geomean_eager={gm_e}, fast_1_eager={fe[1.0]}/{n}")


if __name__ == "__main__":
    main()
